### ISSUE TITLE
Add Licence Data

### ISSUE THREAD

**Issue by phillord** [geneontology/protege-tutorial#1]
It would be nice to add some licenses to this repo, both for the OWL files and the documentation!

**Comment by cmungall** [comment]
@simonjupp @dosumis OK with CC-BY as in the PR?

**Comment by dosumis** [comment]
Fine with me.  For CC-BY should spec how we wish to be attributed.

**Comment by phillord** [comment]
Ta!

BTW, the same sort of applies to the plant fork. You switched the issue tracker off on that one:-)
